# Generated by Django 4.2.5 on 2023-10-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='chouma',
            field=models.IntegerField(default=1000),
        ),
    ]
