# Generated by Django 4.2.5 on 2023-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_avatar_user_chouma'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quyu1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='quyu2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='quyu3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='quyu4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='quyu5',
            field=models.IntegerField(default=0),
        ),
    ]
