# Generated by Django 4.2.5 on 2023-10-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_quyu1_user_quyu2_user_quyu3_user_quyu4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='quyu1',
            new_name='tou1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='quyu2',
            new_name='tou2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='quyu3',
            new_name='tou3',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='quyu4',
            new_name='tou4',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='quyu5',
            new_name='tou5',
        ),
        migrations.AddField(
            model_name='user',
            name='xuan1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='xuan2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='xuan3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='xuan4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='xuan5',
            field=models.IntegerField(default=0),
        ),
    ]
