# Generated by Django 4.2.5 on 2023-10-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_quyu1_user_tou1_rename_quyu2_user_tou2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beilv',
            field=models.IntegerField(default=0),
        ),
    ]
