# Generated by Django 4.2.5 on 2023-10-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_beilv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='beilv',
            new_name='pipeizhuangtai',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tou1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tou2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tou3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tou4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tou5',
        ),
        migrations.AddField(
            model_name='user',
            name='lishijilu',
            field=models.TextField(default=''),
        ),
    ]
